config/routes.rb
Badgedin3::Application.routes.draw do

  resources :experts


  resources :socialreviews


  resources :seoreviews


  resources :ppcreviews


  resources :messages
  match "/contact", to: "messages#new"

  resources :badges

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  
  match "/plans", to: "plans#index"
  match "/library", to: "library#index"
  match "/basics_ppc", to: "library#basics_ppc"
  match "/basics_seo", to: "library#basics_seo"
  match "/basics_social", to: "library#basics_social"
  match "/starter", to: "starter#index"
  match "/strategy_sessions", to: "strategysessions#index"
  match "/privacy", to: "legal#privacy"
  match "/terms", to: "legal#terms"
  match "/about", to: "legal#about"
  match "/tools", to: "tools#index"
  match "/welcome/silver", to: "welcome#silver"
  match "/welcome/gold", to: "welcome#gold"
  match "/welcome/platinum", to: "welcome#platinum"
  
  match "/basics_ppc/how_se_work/organic_ppc", to: "basics_ppc#howsework_organic_ppc"
  match "/basics_ppc/how_se_work/web_crawlers", to: "basics_ppc#howsework_webcrawlers" 
  match "/basics_ppc/how_se_work/why", to: "basics_ppc#howsework_why" 
  match "/basics_ppc/PPC_101/bids", to: "basics_ppc#ppc101_bid"
  match "/basics_ppc/PPC_101/rankings", to: "basics_ppc#ppc101_rankings"
  match "/basics_ppc/PPC_101/google_quatlity_score", to: "basics_ppc#ppc101_google_qs"
  match "/basics_ppc/PPC_101/quality_score", to: "basics_ppc#ppc101_qs"
  match "/basics_ppc/PPC_101/intro_to_ppc", to: "basics_ppc#ppc101"
  match "/basics_ppc/search_engine_structure/ad_groups", to: "basics_ppc#sestructure_adgroups"
  match "/basics_ppc/search_engine_structure/campaigns", to: "basics_ppc#sestructure_campaigns"
  match "/basics_ppc/search_engine_structure/keywords", to: "basics_ppc#sestructure_keywords"
  match "/basics_ppc/search_engine_structure/matchtypes", to: "basics_ppc#sestructure_matchtypes"
  match "/basics_ppc/search_engine_structure/overview", to: "basics_ppc#sestructure_overview"
  match "/basics_ppc/tracking_and_reporting/metrics", to: "basics_ppc#trackingreporting_metrics"
  match "/basics_ppc/tracking_and_reporting/reporting", to: "basics_ppc#trackingreporting_reporting"
  match "/basics_ppc/tracking_and_reporting/tracking", to: "basics_ppc#trackingreporting_tracking"
  
  match "/basics_seo/how_se_work/organic_ppc", to: "basics_seo#howsework_organic_ppc"
  match "/basics_seo/how_se_work/web_crawlers", to: "basics_seo#howsework_webcrawlers" 
  match "/basics_seo/how_se_work/why", to: "basics_seo#howsework_why"
  match "/basics_seo/offsite/alternative_solutions", to: "basics_seo#offsite_alternative_solutions"
  match "/basics_seo/offsite/articles", to: "basics_seo#offsite_articles"
  match "/basics_seo/offsite/directories_and_forums", to: "basics_seo#offsite_directories_forums"
  match "/basics_seo/offsite/guest_posts_and_comments", to: "basics_seo#offsite_guestposts_comments"
  match "/basics_seo/offsite/overview", to: "basics_seo#offsite_overview"
  match "/basics_seo/offsite/promotional", to: "basics_seo#offsite_promotional"
  match "/basics_seo/onsite/freshness", to: "basics_seo#onsite_freshness"
  match "/basics_seo/onsite/keywords", to: "basics_seo#onsite_keywords"
  match "/basics_seo/onsite/links", to: "basics_seo#onsite_links"
  match "/basics_seo/onsite/meta_and_title_tags", to: "basics_seo#onsite_metatitletags"
  match "/basics_seo/onsite/sitemap", to: "basics_seo#onsite_sitemap"
  match "/basics_seo/se_tools/bing_webmaster", to: "basics_seo#setools_bing_webmaster"
  match "/basics_seo/se_tools/common_settings", to: "basics_seo#setools_common_settings"
  match "/basics_seo/se_tools/google_webmaster", to: "basics_seo#setools_google_webmaster"
  match "/basics_seo/seo101/intro_to_seo", to: "basics_seo#seo101"
  match "/basics_seo/seo101/onsite_offsite", to: "basics_seo#seo101_onsiteoffsite"
  match "/basics_seo/seo101/websites", to: "basics_seo#seo101_websites"
  match "/basics_seo/tracking_and_reporting/free_tools", to: "basics_seo#trackingreporting_freetools"
  match "/basics_seo/tracking_and_reporting/metrics", to: "basics_seo#trackingreporting_metrics"
  match "/basics_seo/tracking_and_reporting/paid_tools", to: "basics_seo#trackingreporting_paidtools"
  match "/basics_seo/tracking_and_reporting/reports", to: "basics_seo#trackingreporting_reports"
  
  match "/basics_social/fb_admin/basics", to: "basics_social#fbadmin_basic"
  match "/basics_social/fb_admin/complete", to: "basics_social#fbadmin_complete"
  match "/basics_social/fb_engage_measure/engagement", to: "basics_social#fbengagemeasure_engagement"
  match "/basics_social/fb_engage_measure/measurement", to: "basics_social#fbengagemeasure_measurement"
  match "/basics_social/fb_likes/part1", to: "basics_social#fblikes"
  match "/basics_social/fb_likes/part2", to: "basics_social#fblikes2"
  match "/basics_social/fb_likes/part3", to: "basics_social#fblikes3"
  match "/basics_social/fb_timeline/part1", to: "basics_social#fbtimeline"
  match "/basics_social/fb_timeline/part2", to: "basics_social#fbtimeline2"
  match "/basics_social/fb_timeline/part3", to: "basics_social#fbtimeline3"
  match "/basics_social/twitter_basics/part1", to: "basics_social#twitterbasics1"
  match "/basics_social/twitter_basics/part2", to: "basics_social#twitterbasics2"
  match "/basics_social/twitter_basics/part3", to: "basics_social#twitterbasics3"
  match "/basics_social/twitter_basics/part4", to: "basics_social#twitterbasics4"
  match "/basics_social/twitter_management/lists", to: "basics_social#twittermanage_lists"
  match "/basics_social/twitter_management/search", to: "basics_social#twittermanage_search"
  match "/basics_social/twitter_management/thirdpartyapps", to: "basics_social#twittermanage_thirdpartyapps"
  
  match "/basics_ppc/how_se_work/quiz", to: "basicsquizzes_ppc#howsework_quiz"
  match "/basics_ppc/how_se_work/badge", to: "basicsquizzes_ppc#howsework_badge"
  match "/basics_ppc/PPC_101/quiz", to: "basicsquizzes_ppc#ppc101_quiz"
  match "/basics_ppc/PPC_101/badge", to: "basicsquizzes_ppc#ppc101_badge"
  match "/basics_ppc/search_engine_structure/quiz", to: "basicsquizzes_ppc#sestructure_quiz"
  match "/basics_ppc/search_engine_structure/badge", to: "basicsquizzes_ppc#sestructure_badge"
  match "/basics_ppc/tracking_and_reporting/quiz", to: "basicsquizzes_ppc#trackingreporting_quiz"
  match "/basics_ppc/tracking_and_reporting/badge", to: "basicsquizzes_ppc#trackingreporting_badge"

  match "/basics_seo/how_se_work/quiz", to: "basicsquizzes_seo#howsework_quiz"
  match "/basics_seo/how_se_work/badge", to: "basicsquizzes_seo#howsework_badge"
  match "/basics_seo/offsite/quiz", to: "basicsquizzes_seo#offsite_quiz"
  match "/basics_seo/offsite/badge", to: "basicsquizzes_seo#offsite_badge"
  match "/basics_seo/onsite/quiz", to: "basicsquizzes_seo#onsite_quiz"
  match "/basics_seo/onsite/badge", to: "basicsquizzes_seo#onsite_badge"
  match "/basics_seo/seo101/quiz", to: "basicsquizzes_seo#seo101_quiz"
  match "/basics_seo/seo101/badge", to: "basicsquizzes_seo#seo101_badge"
  match "/basics_seo/se_tools/quiz", to: "basicsquizzes_seo#setools_quiz"
  match "/basics_seo/se_tools/badge", to: "basicsquizzes_seo#setools_badge"
  match "/basics_seo/tracking_and_reporting/quiz", to: "basicsquizzes_seo#trackingreporting_quiz"
  match "/basics_seo/tracking_and_reporting/badge", to: "basicsquizzes_seo#trackingreporting_badge"
 
  match "/basics_social/fb_admin/quiz", to: "basicsquizzes_social#fbadmin_quiz"
  match "/basics_social/fb_admin/badge", to: "basicsquizzes_social#fbadmin_badge"
  match "/basics_social/fb_engage_measure/quiz", to: "basicsquizzes_social#fbengagemeasure_quiz"
  match "/basics_social/fb_engage_measure/badge", to: "basicsquizzes_social#fbengagemeasure_badge"
  match "/basics_social/fb_likes/quiz", to: "basicsquizzes_social#fblikes_quiz"
  match "/basics_social/fb_likes/badge", to: "basicsquizzes_social#fblikes_badge"
  match "/basics_social/fb_timeline/quiz", to: "basicsquizzes_social#fbtimeline_quiz"
  match "/basics_social/fb_timeline/badge", to: "basicsquizzes_social#fbtimeline_badge"
  match "/basics_social/twitter_basics/quiz", to: "basicsquizzes_social#twitterbasics_quiz"
  match "/basics_social/twitter_basics/badge", to: "basicsquizzes_social#twitterbasics_badge"
  match "/basics_social/twitter_management/quiz", to: "basicsquizzes_social#twittermanage_quiz"
  match "/basics_social/twitter_management/badge", to: "basicsquizzes_social#twittermanage_badge"
  
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% title 'Learn to market and advertise your website' %>
<% description 'Start your 30 day free trial today!  BadgedIn is the fastest, easiest way to learn how to market and advertise your website with Social Media, PPC, and SEO.' %>

<div class="row hero-unit">
  <div class="herocontain">
  <div class="heading pull-left">
    <h1 class="lead" align="center">Online Marketing. Simplified.</h1>
    <h3 class="lead" align="center">Learn to market and advertise your website.</h3>
    <p align="center"><%= link_to 'View the library', library_path, class: 'btn-custom2' %></p>
  </div>
  <div class="imgheading pull-right hidden-phone">
    <p align="center"><%= image_tag("https://s3.amazonaws.com/badgedin/images/hp_overview2600.png") %></p>
  </div>
  </div>
</div>
	  
<div class="container">
  <div class="content">
	<div class="row">
      <div class="span12">
		<ul class="nav nav-tabs">
		  <li class="active"><a href="#tab1" data-toggle="tab"><%= image_tag("https://s3.amazonaws.com/badgedin/badges/ppc_badge3150.png") %></a><p class="lead">PPC</p></li>
		  <li><a href="#tab2" data-toggle="tab"><%= image_tag("https://s3.amazonaws.com/badgedin/badges/social_media_badge150.png") %></a><p class="lead">Social</p></li>
		  <li><a href="#tab3" data-toggle="tab"><%= image_tag("https://s3.amazonaws.com/badgedin/badges/seo_badge3150.png") %></a><p class="lead">SEO</p></li>
		</ul>
		<div class="tab-content">
		  <div class="tab-pane active" id="tab1">
		    <h2 align="center" class="hidden-phone">Pay Per Click</h2>
		      <div class="span3 hpspan">
			    <h3 align="center">Learn the basics</h3>
			    <p align="center"><%= image_tag("https://s3.amazonaws.com/badgedin/images/ppc_basics100.png") %></p>
			    <p>We'll take you from zero to knowing what PPC can do for your business.</p>
			  </div>
			  <div class="span3">
			    <h3 align="center">Create a strategy</h3>
			    <p align="center"><%= image_tag("https://s3.amazonaws.com/badgedin/images/ppc_strategy100.png") %></p>
			    <p>Once you know the basics you can begin planning how PPC will help you.</p>
			  </div>
			  <div class="span3">
			    <h3 align="center">Build your campaign</h3>
			    <p align="center"><%= image_tag("https://s3.amazonaws.com/badgedin/images/ppc_build100.png") %></p>
			    <p>With the basics and strategy in place it's time to create your PPC campaign.</p>
			  </div>
		  </div>
		  <div class="tab-pane" id="tab2">
		    <h2 align="center" class="hidden-phone">Social Media</h2>
			  <div class="span3 hpspan">
			    <h3 align="center">Learn the basics</h3>
			    <p align="center"><%= image_tag("https://s3.amazonaws.com/badgedin/images/social_basics100.png") %></p>			    
			    <p>We'll take you from zero to knowing what Social Media can do for your business.</p>
			  </div>
			  <div class="span3">
			    <h3 align="center">Create a strategy</h3>
			      <p align="center"><%= image_tag("https://s3.amazonaws.com/badgedin/images/social_strategy100.png") %></p>
			    <p>Once you know the basics you can begin planning how Social Media will help you.</p>
			  </div>
			  <div class="span3">
			    <h3 align="center">Share your business</h3>
			    <p align="center"><%= image_tag("https://s3.amazonaws.com/badgedin/images/social_social100.png") %></p>
			    <p>With the basics and strategy in place it's time to use Social Media.</p>
			  </div>
		  </div>
		  <div class="tab-pane" id="tab3">
		    <h2 align="center" class="hidden-phone">Search Engine Optimization</h2>
		      <div class="span3 hpspan">
			    <h3 align="center">Learn the basics</h3>
			    <p align="center"><%= image_tag("https://s3.amazonaws.com/badgedin/images/seo_basics100.png") %></p>
			    <p>We'll take you from zero to knowing what SEO can do for your website.</p>
			  </div>
			  <div class="span3">
			    <h3 align="center">Create a strategy</h3>
			    <p align="center"><%= image_tag("https://s3.amazonaws.com/badgedin/images/seo_strategy100.png") %></p>
			    <p>Once you know the basics you can begin planning how SEO will help you.</p>
			  </div>
			  <div class="span3">
			    <h3 align="center">Optimize your site</h3>
			    <p align="center"><%= image_tag("https://s3.amazonaws.com/badgedin/images/seo_optimize100.png") %></p>
			    <p>With the basics and strategy in place it's time to use SEO tactics.</p>
			  </div>
		  </div>
		</div>
	  </div>
	</div>
	<div class="row">
	  <div class="span12">
	    <br />
	    <br />
		<h2 align="center"><%= link_to 'Start your free trial', plans_path, class: 'btn-custom3' %></h2>
		<br />
	  </div>
	</div>
  </div>
</div>